### ISSUE TITLE
programming language

### ISSUE THREAD

**Issue by Pantyhose-X** [GabeRundlett/gvox_engine#10]
Should the use a programming language that is faster, smaller, and consumes less resources?
?
 It's 2024 and not many people are going to learn languages like C and java, which are not 
easy to learn and consume more time to maintain.
[Odin](https://github.com/odin-lang/Odin), [Nelua](https://github.com/edubart/nelua-lang) ,[Rust](https://github.com/rust-lang/rust) , [Zig](https://github.com/ziglang/zig)

**Comment by GabeRundlett** [comment]
Could you elaborate?

**Comment by RedNicStone** [comment]
Who let chatgpt loose on github?

**Comment by trsh** [comment]
> Who let chatgpt loose on github?

Meh, no, chatGPT writes correct sentences.

**Comment by trsh** [comment]
> Should the use a programming language that is faster, smaller, and consumes less resources? ? It's 2024 and not many people are going to learn languages like C and java, which are not easy to learn and consume more time to maintain. [Odin](https://github.com/odin-lang/Odin), [Nelua](https://github.com/edubart/nelua-lang) ,[Rust](https://github.com/rust-lang/rust) , [Zig](https://github.com/ziglang/zig)

Some issues with your question / proposal. This engine is writen in c++, not c, big difference.
Try to actually use Rust for some more or less complex project and then talk about "it being easier to learn and maintain". More trending then c++, sure, but easier to code, no way (maybe just the building part).
So we are left with odin and zig (can't comment on nelua, as I haven't researched it). But why do you think zig/odin are smaller and faster, and use less resources? Actually for that c/c++/rust are best candidates and should in deed power the core of a desktop voxel engine. 
For a more high level programming, there is usually an API/SDK that can power many language bindings. Maybe that is the thing you wish for?

**Comment by Pantyhose-X** [comment]
Test data from benchmark
https://survey.stackoverflow.co/2023/ According to the statistics, the number of people learning c, cpp, java is decreasing.
https://programming-language-benchmarks.vercel.app/cpp-vs-zig
https://programming-language-benchmarks.vercel.app/cpp-vs-rust
https://programming-language-benchmarks.vercel.app/cpp-vs-odin

**Comment by solmidnight** [comment]
A language like CPP still has a lot of momentum, thus market share. Zig and Rust are both bare-metal languages like C++, they are not significantly faster or slower nor do they consume a significantly different amount of resources.

To top it off, this is a gpu driven engine; even if this was written in java most of the work is being done by the gpu.
If anything we need a more advanced shader language! 😊

**Comment by solmidnight** [comment]
> Test data from benchmark https://survey.stackoverflow.co/2023/ According to the statistics, the number of people learning c, cpp, java is decreasing. https://programming-language-benchmarks.vercel.app/cpp-vs-zig https://programming-language-benchmarks.vercel.app/cpp-vs-rust https://programming-language-benchmarks.vercel.app/cpp-vs-odin

A language like CPP still has a lot of momentum, thus market share. Zig and Rust are both bare-metal languages like C++, they are not significantly faster or slower nor do they consume a significantly different amount of resources.

To top it off, this is a gpu driven engine; even if this was written in java most of the work is being done by the gpu.
If anything we need a more advanced shader language! 😊

**Comment by trsh** [comment]
> Test data from benchmark https://survey.stackoverflow.co/2023/ According to the statistics, the number of people learning c, cpp, java is decreasing. https://programming-language-benchmarks.vercel.app/cpp-vs-zig https://programming-language-benchmarks.vercel.app/cpp-vs-rust https://programming-language-benchmarks.vercel.app/cpp-vs-odin

- We could start a large dispute, on which programming language is better, and it will go no where, because they are all +/- great for different or same purposes. At the end of the day, it should be evaluated by project needs, i.e. it should get the job done and what works best for the developers.

- Jumping to the next new **Trending** programming language, is not such a great idea actually. Less examples, libraries, and so on. It could have some positive effect, to attract _young blood_ here, but that is not necessary always the ruling factor.

- Is C++ a bad language to learn these days? No! All top dog engines use it. Rockstar Games, the studio behind hit games like Grand Theft Auto and Red Dead Redemption, uses C++ to develop their games. UE5 is powered by C++ and Unity core as well. I could go here on and on with more examples. Actually the only company I know, that does some stuff on Rust, is Embark studios. You don't want to get a chance to work for these top dogs? Because they don't plant to switch to Odin or Zig.

- I have been a software developer now for nearly 21 years. Right now I use Typescript/JavaScript for my web projects, python for machine learning parts, c++, c# (because Unity), verse, glsl/hlsl/wgsl/ and Rust for game dev projects. And honestly I dont care if the next job will throw Odin or Zig at me, if it can get job done, I will learn it in some weeks. There is so much more to being a successful programmer and writing good & performant code, then just picking the "right" or trending language. At some point you wont care and see how much in common those languages have. Rust is actually the most Alien one and hardest to learn, and there are a lot of Opinions on its place in gaming industry.
